const appState={summary:null};const el=id=>document.getElementById(id);
const duration=s=>{s=Number(s);if(!Number.isFinite(s))return'—';const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h} h ${String(m).padStart(2,'0')}`:`${m} min`};
const time=v=>v?new Date(v).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'}):'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activeStage(c){return c?.stages?.find(s=>s.status==='IN_PROGRESS')||c?.stages?.at(-1)}
function renderCycles(data){appState.summary=data;const c=data.active_cycle,s=activeStage(c);el('sum-stage').textContent=s?.stage_name||'Sin ciclo activo';el('sum-stage-time').textContent=s?`En curso · ${duration(s.duration_seconds)}`:'—';el('sum-duration').textContent=c?duration(c.duration_seconds):duration(data.average_duration_seconds);el('sum-advance').textContent=`${Number(data.advance_meters||0).toFixed(1)} m`;el('cycles-total').textContent=data.cycles_total||0;el('cycles-avg').textContent=duration(data.average_duration_seconds);el('cycles-stage').textContent=s?.stage_name||'—';el('cycles-advance').textContent=`${Number(data.advance_meters||0).toFixed(1)} m`;el('cycle-name').textContent=c?`Ciclo activo · ${c.cycle_id}`:'Ciclo activo';el('cycle-meta').textContent=c?`Inicio ${time(c.started_at)} · objetivo ${duration(c.target_duration_seconds)}`:'Sin eventos';
el('stage-list').innerHTML=c?.stages?.length?c.stages.map((x,i)=>`<div class="stage ${x.status==='IN_PROGRESS'?'current':''}"><i>${x.status==='COMPLETED'?'✓':i+1}</i><div><b>${esc(x.stage_name)}</b><small>${time(x.started_at)}–${time(x.ended_at)}</small></div><b>${duration(x.duration_seconds)}</b></div>`).join(''):'<p class="empty">El ciclo aparecerá cuando se reciban eventos.</p>';
el('stage-table').innerHTML=c?.stages?.length?c.stages.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.stage_name)}${x.tracked_object==='brazo_hp1'?' · brazo HP1':''}</td><td>${time(x.started_at)}</td><td>${time(x.ended_at)}</td><td>${duration(x.duration_seconds)}</td><td>${duration(x.target_duration_seconds)}</td><td>${x.deviation_seconds>0?'+':''}${duration(Math.abs(x.deviation_seconds))}</td><td><span class="status ${x.status==='IN_PROGRESS'?'running':''}">${x.status==='COMPLETED'?'Terminado':'En curso'}</span></td></tr>`).join(''):'<tr><td colspan="8" class="empty">Sin ciclo activo</td></tr>';
const recent=data.recent_cycles||[];el('history-table').innerHTML=recent.length?recent.map(x=>`<tr><td>${esc(x.cycle_id)}</td><td>${new Date(x.started_at).toLocaleString('es-CL')}</td><td>${esc(x.shift)}</td><td>${esc(x.front)}</td><td>${duration(x.duration_seconds)}</td><td>${duration(x.target_duration_seconds)}</td><td>${Number(x.advance_meters||0).toFixed(1)} m</td><td><span class="status ${x.status==='IN_PROGRESS'?'running':''}">${x.status==='COMPLETED'?'Terminado':'En curso'}</span></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No hay ciclos registrados</td></tr>';
const done=recent.filter(x=>x.status==='COMPLETED').slice(0,5).reverse();el('chart').innerHTML=done.length?done.map(x=>{const max=Math.max(x.duration_seconds,x.target_duration_seconds,1);return`<div class="bar-pair"><i style="height:${x.target_duration_seconds/max*90}%"></i><i class="real" style="height:${x.duration_seconds/max*90}%"></i><label>${esc(x.cycle_id)}</label></div>`}).join(''):'<p class="empty">Sin ciclos terminados</p>';
const ev=c?.stages?.filter(x=>x.evidence_url)||[];el('evidence-grid').innerHTML=ev.length?ev.map(x=>`<article class="panel"><img src="${esc(x.evidence_url)}" alt="Evidencia ${esc(x.stage_name)}"><h3>${esc(x.stage_name)}</h3><small>${time(x.started_at)} · confianza ${Math.round((x.confidence||0)*100)}%</small>${x.tracked_object==='brazo_hp1'?`<p>Tiempo visible del brazo: ${duration(x.visible_seconds)}</p>`:''}</article>`).join(''):'<article class="panel empty">Sin evidencias del ciclo.</article>'}
function renderEpp(d){const pct=Number(d.compliance_observed_pct||0);el('sum-epp').textContent=`${pct.toFixed(1)}%`;el('epp-total').textContent=d.events_epp_evaluated||0;el('epp-pct').textContent=`${pct.toFixed(1)}%`;el('epp-fails').textContent=d.events_non_compliant||0;el('epp-missing').textContent=d.most_missing_epp||'—';el('epp-breakdown').innerHTML=(d.epp_breakdown||[]).map(x=>`<div class="epp"><span>${esc(x.name)}</span><b>${Number(x.detected_pct||0).toFixed(1)}%</b><div class="progress"><i style="width:${Number(x.detected_pct||0)}%"></i></div></div>`).join('')||'<p class="empty">Sin evaluaciones EPP</p>'}
async function load(){try{const [cycles,epp]=await Promise.all([fetchAPI('/cycles/summary'),fetchAPI('/dashboard/epp-metrics?minutes=1440')]);renderCycles(cycles);renderEpp(epp);el('connection').textContent='Datos operacionales desde AWS';}catch(e){console.error(e);el('connection').textContent='No fue posible consultar la API'}el('camera-time').textContent=new Date().toLocaleString('es-CL')}
function csv(rows,name){if(!rows?.length)return;const keys=Object.keys(rows[0]),body=[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const id=b.dataset.view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));el('title').textContent={summary:'Resumen operacional',epp:'Control de EPP',cycle:'Ciclo de excavación',evidence:'Evidencias visuales',history:'Historial de ciclos'}[id]});el('refresh').onclick=load;el('export-active').onclick=()=>csv(appState.summary?.active_cycle?.stages,'ciclo-activo-linea9.csv');el('export-history').onclick=()=>csv(appState.summary?.recent_cycles,'historial-ciclos-linea9.csv');document.addEventListener('DOMContentLoaded',()=>{load();setInterval(load,5000)});
