const appState={summary:null};const el=id=>document.getElementById(id);
document.head.insertAdjacentHTML('beforeend','<style>.epp-live-image{width:100%;height:242px;object-fit:contain;border-radius:9px;background:#030b11}.image-caption{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px 4px 0}.image-caption span{color:var(--muted);font-size:13px}.camera-empty{height:242px;display:grid;place-content:center;text-align:center;color:var(--muted)}.camera-empty b,.camera-empty span{display:block}.telemetry{display:grid;grid-template-columns:1fr 1fr;gap:10px}.telemetry div{background:#0a2031;border:1px solid #1c3b4e;border-radius:9px;padding:13px}.telemetry span,.telemetry b{display:block}.telemetry span{color:var(--muted);font-size:12px}.telemetry b{font-size:19px;margin-top:5px}.telemetry .ok{color:var(--green)}.telemetry .offline{color:var(--red)}</style>');
const duration=s=>{s=Number(s);if(!Number.isFinite(s))return'—';const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h} h ${String(m).padStart(2,'0')}`:`${m} min`};
const time=v=>v?new Date(v).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'}):'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activeStage(c){return c?.stages?.find(s=>s.status==='IN_PROGRESS')||c?.stages?.at(-1)}
function renderCycles(data){appState.summary=data;const c=data.active_cycle,s=activeStage(c);el('sum-stage').textContent=s?.stage_name||'Sin ciclo activo';el('sum-stage-time').textContent=s?`En curso · ${duration(s.duration_seconds)}`:'—';el('sum-duration').textContent=c?duration(c.duration_seconds):duration(data.average_duration_seconds);el('sum-advance').textContent=`${Number(data.advance_meters||0).toFixed(1)} m`;el('cycles-total').textContent=data.cycles_total||0;el('cycles-avg').textContent=duration(data.average_duration_seconds);el('cycles-stage').textContent=s?.stage_name||'—';el('cycles-advance').textContent=`${Number(data.advance_meters||0).toFixed(1)} m`;el('cycle-name').textContent=c?`Ciclo activo · ${c.cycle_id}`:'Ciclo activo';el('cycle-meta').textContent=c?`Inicio ${time(c.started_at)} · objetivo ${duration(c.target_duration_seconds)}`:'Sin eventos';
el('stage-list').innerHTML=c?.stages?.length?c.stages.map((x,i)=>`<div class="stage ${x.status==='IN_PROGRESS'?'current':''}"><i>${x.status==='COMPLETED'?'✓':i+1}</i><div><b>${esc(x.stage_name)}</b><small>${time(x.started_at)}–${time(x.ended_at)}</small></div><b>${duration(x.duration_seconds)}</b></div>`).join(''):'<p class="empty">El ciclo aparecerá cuando se reciban eventos.</p>';
el('stage-table').innerHTML=c?.stages?.length?c.stages.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.stage_name)}${x.tracked_object==='brazo_hp1'?' · brazo HP1':''}</td><td>${time(x.started_at)}</td><td>${time(x.ended_at)}</td><td>${duration(x.duration_seconds)}</td><td>${duration(x.target_duration_seconds)}</td><td>${x.deviation_seconds>0?'+':''}${duration(Math.abs(x.deviation_seconds))}</td><td><span class="status ${x.status==='IN_PROGRESS'?'running':''}">${x.status==='COMPLETED'?'Terminado':'En curso'}</span></td></tr>`).join(''):'<tr><td colspan="8" class="empty">Sin ciclo activo</td></tr>';
const recent=data.recent_cycles||[];el('history-table').innerHTML=recent.length?recent.map(x=>`<tr><td>${esc(x.cycle_id)}</td><td>${new Date(x.started_at).toLocaleString('es-CL')}</td><td>${esc(x.shift)}</td><td>${esc(x.front)}</td><td>${duration(x.duration_seconds)}</td><td>${duration(x.target_duration_seconds)}</td><td>${Number(x.advance_meters||0).toFixed(1)} m</td><td><span class="status ${x.status==='IN_PROGRESS'?'running':''}">${x.status==='COMPLETED'?'Terminado':'En curso'}</span></td></tr>`).join(''):'<tr><td colspan="8" class="empty">No hay ciclos registrados</td></tr>';
const done=recent.filter(x=>x.status==='COMPLETED').slice(0,5).reverse();el('chart').innerHTML=done.length?done.map(x=>{const max=Math.max(x.duration_seconds,x.target_duration_seconds,1);return`<div class="bar-pair"><i style="height:${x.target_duration_seconds/max*90}%"></i><i class="real" style="height:${x.duration_seconds/max*90}%"></i><label>${esc(x.cycle_id)}</label></div>`}).join(''):'<p class="empty">Sin ciclos terminados</p>';
const ev=c?.stages?.filter(x=>x.evidence_url)||[];el('evidence-grid').innerHTML=ev.length?ev.map(x=>`<article class="panel"><img src="${esc(x.evidence_url)}" alt="Evidencia ${esc(x.stage_name)}"><h3>${esc(x.stage_name)}</h3><small>${time(x.started_at)} · confianza ${Math.round((x.confidence||0)*100)}%</small>${x.tracked_object==='brazo_hp1'?`<p>Tiempo visible del brazo: ${duration(x.visible_seconds)}</p>`:''}</article>`).join(''):'<article class="panel empty">Sin evidencias del ciclo.</article>'}
function renderEpp(d){const pct=Number(d.compliance_observed_pct||0),required=(d.epp_breakdown||[]).filter(x=>['casco','chaleco reflectante'].includes(String(x.name).toLowerCase()));el('sum-epp').textContent=`${pct.toFixed(1)}%`;el('epp-total').textContent=d.events_epp_evaluated||0;el('epp-pct').textContent=`${pct.toFixed(1)}%`;el('epp-fails').textContent=d.events_non_compliant||0;el('epp-missing').textContent=d.most_missing_epp||'—';el('epp-breakdown').innerHTML=required.map(x=>`<div class="epp"><span>${esc(x.name)}</span><b>${Number(x.detected_pct||0).toFixed(1)}%</b><div class="progress"><i style="width:${Number(x.detected_pct||0)}%"></i></div></div>`).join('')||'<p class="empty">Sin evaluaciones de casco y chaleco</p>'}
function renderLive(images,lora){
 const latest=[...(images?.non_compliant||[]),...(images?.compliant||[])].sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp))[0],camera=document.querySelector('.camera');
 camera.innerHTML=latest?`<time>${new Date(latest.timestamp).toLocaleString('es-CL')}</time><img class="epp-live-image" src="${esc(latest.image_url)}" alt="Última imagen de personas con casco y chaleco"><div class="image-caption"><b>Casco y chaleco evaluados</b><span>${latest.workers_detected||0} persona(s) · ${Number(latest.overall_compliance_percentage||0).toFixed(1)}% cumplimiento</span></div>`:`<div class="camera-empty"><b>Esperando imagen EPP</b><span>La última captura procesada aparecerá aquí.</span></div>`;
 const k=document.querySelectorAll('#summary .kpis article');k[1].querySelector('label').textContent='Gateway LoRa';k[1].querySelector('strong').textContent=lora?.device_status||'Offline';k[1].querySelector('small').textContent=lora?.last_seen?`Último dato ${new Date(lora.last_seen).toLocaleString('es-CL')}`:'Sin telemetría reciente';k[2].querySelector('label').textContent='Rocas detectadas';k[2].querySelector('strong').textContent=lora?.rocas_detectadas??0;k[2].querySelector('small').textContent=`Riesgo ${lora?.current_risk_level||'LOW'}`;k[3].querySelector('label').textContent='Avance por LoRa';k[3].querySelector('strong').textContent=`${Number(lora?.avance_metros||0).toFixed(1)} m`;k[3].querySelector('small').textContent=`Deslizamientos: ${lora?.deslizamientos??0}`;
 el('cycle-name').textContent='Telemetría del túnel';el('cycle-meta').textContent='Gateway LoRaWAN · Milesight UG65';el('stage-list').innerHTML=`<div class="telemetry"><div><span>Estado</span><b class="${lora?.device_status==='Online'?'ok':'offline'}">${esc(lora?.device_status||'Offline')}</b></div><div><span>Rocas detectadas</span><b>${lora?.rocas_detectadas??0}</b></div><div><span>Deslizamientos</span><b>${lora?.deslizamientos??0}</b></div><div><span>Avance informado</span><b>${Number(lora?.avance_metros||0).toFixed(2)} m</b></div><div><span>Nivel de riesgo</span><b>${esc(lora?.current_risk_level||'LOW')}</b></div><div><span>Alarmas</span><b>${lora?.total_alarms_triggered??0}</b></div></div>`;
}
async function load(){try{const [cycles,epp,images,lora]=await Promise.all([fetchAPI('/cycles/summary'),fetchAPI('/dashboard/epp-metrics?minutes=1440'),fetchAPI('/dashboard/latest-images?limit=1'),fetchAPI('/dashboard/excavation')]);renderCycles(cycles);renderEpp(epp);renderLive(images,lora);el('connection').textContent='Cámaras EPP y gateway LoRa conectados';}catch(e){console.error(e);el('connection').textContent='No fue posible consultar la API'}}
function csv(rows,name){if(!rows?.length)return;const keys=Object.keys(rows[0]),body=[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const id=b.dataset.view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));el('title').textContent={summary:'Resumen operacional',epp:'Control de EPP',cycle:'Ciclo de excavación',evidence:'Evidencias visuales',history:'Historial de ciclos'}[id]});el('refresh').onclick=load;el('export-active').onclick=()=>csv(appState.summary?.active_cycle?.stages,'ciclo-activo-linea9.csv');el('export-history').onclick=()=>csv(appState.summary?.recent_cycles,'historial-ciclos-linea9.csv');document.addEventListener('DOMContentLoaded',()=>{load();setInterval(load,5000)});
